require('dotenv').config();
const express=require('express');const session=require('express-session');const pgSession=require('connect-pg-simple')(session);const methodOverride=require('method-override');const path=require('path');const http=require('http');const {Server:SocketIOServer}=require('socket.io');
const db=require('./config/db');const {attachUser}=require('./middleware/auth');const {formatVND,formatDate,embedVideoInfo,embedPdfUrl}=require('./utils');const Settings=require('./models/Settings');const NavMenuItem=require('./models/NavMenuItem');const Popup=require('./models/Popup');
const app=express();const PORT=process.env.PORT||3000;process.on('unhandledRejection',reason=>console.error('>>> Unhandled Rejection:',reason));process.on('uncaughtException',err=>console.error('>>> Uncaught Exception:',err));
const wrapAsync=fn=>{if(typeof fn!=='function'||fn.length>=4)return fn;return function(req,res,next){Promise.resolve(fn(req,res,next)).catch(next)}};['get','post','put','delete','patch','all'].forEach(method=>{const original=express.Router[method];express.Router[method]=function(route,...handlers){return original.call(this,route,...handlers.map(wrapAsync))}});
app.set('view engine','ejs');app.set('views',path.join(__dirname,'views'));app.use(express.urlencoded({extended:true,limit:'50mb'}));app.use(express.json({limit:'50mb'}));app.use(methodOverride('_method'));app.use(express.static(path.join(__dirname,'public')));
const sessionStore=new pgSession({pool:db.pool,tableName:'session'});const sessionMiddleware=session({store:sessionStore,secret:process.env.SESSION_SECRET||'thay-doi-chuoi-bi-mat-nay',resave:false,saveUninitialized:false,cookie:{maxAge:30*24*60*60*1000}});app.use(sessionMiddleware);app.use(attachUser);
app.use((req,res,next)=>{res.locals.formatVND=formatVND;res.locals.formatDate=formatDate;res.locals.embedVideoInfo=embedVideoInfo;res.locals.embedPdfUrl=embedPdfUrl;res.locals.path=req.path;res.locals.req=req;next()});
app.use(async(req,res,next)=>{try{const [all,rawNavItems,popup]=await Promise.all([Settings.getAll(),NavMenuItem.active(),Popup.activeOne()]);const corePaths=new Set(['/','/khoa-hoc','/phong-hoc','/sach','/doc-sach-online','/dang-nhap','/dang-ky']);const seen=new Set();const navItems=rawNavItems.filter(item=>{const url=String(item.url||'').trim().replace(/\/$/,'')||'/';if(corePaths.has(url))return false;const key=url+'|'+String(item.label||'').trim().toLowerCase();if(seen.has(key))return false;seen.add(key);return true});res.locals.site={site_name_1:all.site_name_1||'Học',site_name_2:all.site_name_2||'Online',hero_title:all.hero_title||'Học mọi lúc, mọi nơi',hero_subtitle:all.hero_subtitle||'Nền tảng học tập trực tuyến.',footer_text:all.footer_text||'Vào Học Nào — Nền tảng học tập trực tuyến',left_side_image:all.left_side_image||'',left_side_link:all.left_side_link||'',right_side_image:all.right_side_image||'',right_side_link:all.right_side_link||'',footer_logo:all.footer_logo||'',footer_link:all.footer_link||''};res.locals.navItems=navItems;res.locals.activePopup=popup||null;const customDomain=(all.custom_domain||'').trim().toLowerCase();if(customDomain&&req.hostname&&req.hostname.toLowerCase()===customDomain&&req.path==='/')return res.redirect(all.custom_domain_path||'/truyen')}catch(e){res.locals.site={site_name_1:'Học',site_name_2:'Online',hero_title:'Học mọi lúc, mọi nơi',hero_subtitle:'Nền tảng học tập trực tuyến.',footer_text:'Vào Học Nào',left_side_image:'',left_side_link:'',right_side_image:'',right_side_link:'',footer_logo:'',footer_link:''};res.locals.navItems=[];res.locals.activePopup=null}next()});
app.use('/',require('./routes/site'));app.use('/',require('./routes/auth'));app.use('/',require('./routes/student'));app.use('/',require('./routes/bookQuiz'));app.use('/',require('./routes/classroom'));app.use('/webhook',require('./routes/webhook'));app.use('/admin',require('./routes/admin'));app.use('/admin',require('./routes/bookQuizAdmin'));
app.use((req,res)=>res.status(404).render('404'));app.use((err,req,res,next)=>{console.error(err);res.status(500).send(`<pre style="white-space:pre-wrap;font-family:monospace;padding:20px;color:#b5433a">Đã xảy ra lỗi máy chủ.\n\nTrang: ${req.method} ${req.originalUrl}\nLỗi: ${err.message}\n\nChi tiết kỹ thuật:\n${err.stack||''}</pre>`)});
const httpServer=http.createServer(app);const io=new SocketIOServer(httpServer,{cors:{origin:true,credentials:true},maxHttpBufferSize:4e6});app.locals.io=io;io.engine.use(sessionMiddleware);
const liveViewState=new Map();
const publishedNotes=new Map();
const syncActive=new Map();
const lastSnapshot=new Map();
const cameraActive=new Map();
function emitPresence(room){io.to(`classroom:${room}`).emit('classroom:presence',{count:io.sockets.adapter.rooms.get(`classroom:${room}`)?.size||0})}function socketUser(socket){const s=socket.request?.session||{};return s.adminUser||s.user||null}function socketMemberId(socket,roomId){const s=socket.request?.session||{};return s.classroomMembers?.[roomId]||null}
io.on('connection',socket=>{
 socket.on('classroom:join',async({room})=>{try{if(!room)return;const roomRow=(await db.query('SELECT id,teacher_id,status FROM classrooms WHERE room_code=$1',[room])).rows[0];if(!roomRow||!['live','closed'].includes(roomRow.status)){socket.emit('classroom:error',{message:'Phòng học không tồn tại hoặc đã đóng.'});return}const user=socketUser(socket),teacher=Boolean(user&&(Number(user.id)===Number(roomRow.teacher_id)||['super_admin','admin'].includes(user.role)));let member=null;if(!teacher){if(user?.id)member=(await db.query("SELECT * FROM classroom_students WHERE classroom_id=$1 AND user_id=$2 AND status='active' LIMIT 1",[roomRow.id,user.id])).rows[0]||null;if(!member){const sid=socketMemberId(socket,roomRow.id);if(sid)member=(await db.query("SELECT * FROM classroom_students WHERE classroom_id=$1 AND id=$2 AND status='active'",[roomRow.id,sid])).rows[0]||null}if(!member){socket.emit('classroom:access-required');return}}socket.join(`classroom:${room}`);socket.data.room=room;socket.data.roomId=roomRow.id;socket.data.roomStatus=roomRow.status;socket.data.teacherId=roomRow.teacher_id;socket.data.role=teacher?'teacher':'student';socket.data.user=teacher?(user?.name||'Giáo viên'):(member.display_name||'Học viên');socket.data.studentId=member?.id||null;socket.data.canWrite=teacher||Boolean(member?.can_write);if(member)await db.query('UPDATE classroom_students SET last_seen=now() WHERE id=$1',[member.id]);socket.emit('classroom:permissions',{canWrite:socket.data.canWrite,isTeacher:teacher});const state=liveViewState.get(room);if(state&&roomRow.status==='live')socket.emit('classroom:view-state',state);const note=publishedNotes.get(room);if(note&&!teacher)socket.emit('classroom:note-publish',note);if(!teacher){const syncOn=syncActive.get(room)||false;socket.emit('classroom:view-sync-toggle',{on:syncOn});if(syncOn){const snap=lastSnapshot.get(room);if(snap)socket.emit('classroom:view-snapshot',snap)}if(cameraActive.get(room))socket.emit('classroom:camera-on',{id:null})}socket.to(`classroom:${room}`).emit('classroom:peer-joined',{id:socket.id,role:socket.data.role,user:socket.data.user});emitPresence(room)}catch(e){console.error('classroom join:',e);socket.emit('classroom:error',{message:'Không thể vào phòng học.'})}});
 socket.on('classroom:board',payload=>{if(!socket.data.room)return;const data=payload?.data||{};const kind=String(data.kind||'');const control=['presence-ping','sync-request'].includes(kind);if(control||(socket.data.canWrite&&socket.data.roomStatus==='live'))socket.to(`classroom:${socket.data.room}`).emit('classroom:board',payload)});
 socket.on('classroom:clear',payload=>{if(socket.data.room&&socket.data.canWrite&&socket.data.roomStatus==='live')socket.to(`classroom:${socket.data.room}`).emit('classroom:clear',payload||{})});
 socket.on('classroom:page',payload=>{if(socket.data.room&&socket.data.role==='teacher'&&socket.data.roomStatus==='live'){const p=payload||{};const state=liveViewState.get(socket.data.room)||{};liveViewState.set(socket.data.room,{...state,page:Number.isFinite(Number(p.page))?Number(p.page):0});socket.to(`classroom:${socket.data.room}`).emit('classroom:page',payload)}});
 socket.on('classroom:view-state',payload=>{if(socket.data.room&&socket.data.role==='teacher'&&socket.data.roomStatus==='live'){const p=payload||{};const state={page:Number.isFinite(Number(p.page))?Number(p.page):0,zoom:Math.max(.1,Math.min(5,Number(p.zoom)||1)),panX:Math.max(-100000,Math.min(100000,Number(p.panX)||0)),panY:Math.max(-100000,Math.min(100000,Number(p.panY)||0)),timestamp:Date.now()};liveViewState.set(socket.data.room,state);socket.to(`classroom:${socket.data.room}`).emit('classroom:view-state',state)}});
 socket.on('classroom:note-publish',payload=>{if(!socket.data.room||socket.data.role!=='teacher')return;const p=payload||{};const note={text:String(p.text||'').slice(0,20000),template:String(p.template||'paper').slice(0,20),size:Number(p.size)||16,updatedAt:Date.now()};publishedNotes.set(socket.data.room,note);socket.to(`classroom:${socket.data.room}`).emit('classroom:note-publish',note)});
 socket.on('classroom:note-unpublish',()=>{if(!socket.data.room||socket.data.role!=='teacher')return;publishedNotes.delete(socket.data.room);socket.to(`classroom:${socket.data.room}`).emit('classroom:note-unpublish')});
 socket.on('classroom:pointer',payload=>{if(!socket.data.room||socket.data.role!=='teacher')return;const p=payload||{};const page=Number(p.page);if(!Number.isFinite(page))return;const x=Math.max(0,Math.min(1,Number(p.x)||0)),y=Math.max(0,Math.min(1,Number(p.y)||0));socket.to(`classroom:${socket.data.room}`).emit('classroom:pointer',{page,x,y})});
 socket.on('classroom:material-open',payload=>{if(socket.data.room&&socket.data.role==='teacher'&&socket.data.roomStatus==='live')socket.to(`classroom:${socket.data.room}`).emit('classroom:material-open',payload)});
 socket.on('classroom:write-request',async()=>{
  if(!socket.data.room||socket.data.role!=='student'||!socket.data.studentId)return;
  const setting=(await db.query('SELECT ask_teacher_enabled FROM classroom_settings WHERE classroom_id=$1',[socket.data.roomId])).rows[0];
  if(setting&&setting.ask_teacher_enabled===false){socket.emit('classroom:write-request-denied',{reason:'disabled'});return}
  const s=(await db.query('SELECT display_name,can_write,status FROM classroom_students WHERE id=$1 AND classroom_id=$2',[socket.data.studentId,socket.data.roomId])).rows[0];
  if(!s||s.status!=='active'){socket.emit('classroom:write-request-denied',{reason:'inactive'});return}
  if(s.can_write){socket.emit('classroom:write-request-denied',{reason:'already'});return}
  io.to(`classroom:${socket.data.room}`).emit('classroom:write-request',{userId:socket.data.studentId,user:s.display_name});
  socket.emit('classroom:write-request-sent');
 });
 socket.on('classroom:write-grant',async({userId,allow})=>{if(socket.data.role!=='teacher'||!socket.data.roomId)return;const ok=Boolean(allow);const updated=(await db.query('UPDATE classroom_students SET can_write=$1 WHERE id=$2 AND classroom_id=$3 RETURNING id,can_write',[ok,Number(userId),socket.data.roomId])).rows[0];if(!updated)return;for(const [,s] of io.sockets.sockets){if(s.data.roomId===socket.data.roomId&&Number(s.data.studentId)===Number(updated.id)){s.data.canWrite=ok;s.emit('classroom:write-status',{userId:updated.id,allow:ok})}}});
 socket.on('classroom:write-revoke-all',async()=>{if(socket.data.role!=='teacher'||!socket.data.roomId)return;await db.query('UPDATE classroom_students SET can_write=false WHERE classroom_id=$1',[socket.data.roomId]);for(const [,s] of io.sockets.sockets){if(s.data.roomId===socket.data.roomId&&s.data.role==='student'){s.data.canWrite=false;s.emit('classroom:write-status',{userId:s.data.studentId,allow:false})}}});
 socket.on('classroom:chat',payload=>{if(!socket.data.room)return;const text=String(payload?.text??'').slice(0,500);if(!text.trim())return;io.to(`classroom:${socket.data.room}`).emit('classroom:chat',{user:socket.data.user||'Thành viên',text,at:Date.now(),studentId:socket.data.studentId||null,role:socket.data.role})});
 socket.on('classroom:view-sync-toggle',payload=>{if(!socket.data.room||socket.data.role!=='teacher')return;const on=!!payload?.on;syncActive.set(socket.data.room,on);if(!on)lastSnapshot.delete(socket.data.room);io.to(`classroom:${socket.data.room}`).emit('classroom:view-sync-toggle',{on})});
 socket.on('classroom:view-snapshot',payload=>{if(!socket.data.room||socket.data.role!=='teacher')return;const p=payload||{};const image=typeof p.image==='string'?p.image:'';if(!image||image.length>4000000)return;const pages=Array.isArray(p.pages)?p.pages.slice(0,4).map(x=>({index:Number(x.index)||0,pageX0:Number(x.pageX0)||0,pageY0:Number(x.pageY0)||0,pageX1:Number(x.pageX1)||1,pageY1:Number(x.pageY1)||1,compX0:Number(x.compX0)||0,compY0:Number(x.compY0)||0,compX1:Number(x.compX1)||1,compY1:Number(x.compY1)||1})):[];const state={image,page:Number(p.page)||0,pages,at:Date.now()};lastSnapshot.set(socket.data.room,state);socket.to(`classroom:${socket.data.room}`).emit('classroom:view-snapshot',state)});
 socket.on('webrtc:offer',({to,offer,kind})=>{if(to)io.to(to).emit('webrtc:offer',{from:socket.id,offer,kind})});
 socket.on('webrtc:answer',({to,answer,kind})=>{if(to)io.to(to).emit('webrtc:answer',{from:socket.id,answer,kind})});
 socket.on('webrtc:ice',({to,candidate,kind})=>{if(to)io.to(to).emit('webrtc:ice',{from:socket.id,candidate,kind})});
 socket.on('classroom:camera-on',()=>{if(socket.data.room&&socket.data.role==='teacher'){cameraActive.set(socket.data.room,true);socket.to(`classroom:${socket.data.room}`).emit('classroom:camera-on',{id:socket.id})}});
 socket.on('classroom:camera-off',()=>{if(socket.data.room&&socket.data.role==='teacher'){cameraActive.delete(socket.data.room);socket.to(`classroom:${socket.data.room}`).emit('classroom:camera-off')}});
 socket.on('classroom:camera-request',()=>{if(socket.data.room)socket.to(`classroom:${socket.data.room}`).emit('classroom:camera-request',{id:socket.id})});
 socket.on('classroom:raise-hand',()=>{if(!socket.data.room||socket.data.role!=='student'||!socket.data.studentId)return;io.to(`classroom:${socket.data.room}`).emit('classroom:raise-hand',{userId:socket.data.studentId,user:socket.data.user})});
 socket.on('classroom:mic-grant',({userId,allow})=>{
  if(socket.data.role!=='teacher'||!socket.data.roomId)return;
  const ok=Boolean(allow);let target=null;
  for(const [,s] of io.sockets.sockets){if(s.data.roomId===socket.data.roomId&&Number(s.data.studentId)===Number(userId)){target=s;break}}
  if(!target)return;
  if(ok){
    const peers=[];for(const [,s] of io.sockets.sockets){if(s.data.roomId===socket.data.roomId&&s.id!==target.id)peers.push(s.id)}
    target.emit('classroom:mic-status',{allow:true,peers});
    io.to(`classroom:${socket.data.room}`).emit('classroom:mic-speaking',{userId:Number(userId),user:target.data.user,speaking:true});
  }else{
    target.emit('classroom:mic-status',{allow:false});
  }
 });
 socket.on('classroom:mic-stop',()=>{if(socket.data.room)io.to(`classroom:${socket.data.room}`).emit('classroom:mic-speaking',{userId:socket.data.studentId,speaking:false})});
 socket.on('disconnect',()=>{if(socket.data.room){if(socket.data.role==='teacher'&&cameraActive.get(socket.data.room)){cameraActive.delete(socket.data.room);socket.to(`classroom:${socket.data.room}`).emit('classroom:camera-off')}socket.to(`classroom:${socket.data.room}`).emit('classroom:peer-left',{id:socket.id});setTimeout(()=>emitPresence(socket.data.room),50)}})
});
httpServer.listen(PORT,()=>console.log(`>>> LMS dang chay tai http://localhost:${PORT}`));
