const Book=require('../models/Book'),L=require('../models/BookLearning');
exports.content=async(req,res)=>{const book=await Book.findById(req.params.id);if(!book)return res.redirect('/admin/sach');const chapters=await L.chapters(book.id);const lessons=await L.lessons(book.id);res.render('admin/books/content',{book,chapters,lessons})};
exports.chapterCreate=async(req,res)=>{await L.createChapter(req.body.book_id,req.body.title);res.redirect('/admin/sach/'+req.body.book_id+'/noi-dung')};
exports.chapterReorder=async(req,res)=>{await L.reorderChapters(req.body.ids||[]);res.json({ok:true})};
exports.chapterDelete=async(req,res)=>{await L.deleteChapter(req.params.id);res.redirect('/admin/sach/'+req.body.book_id+'/noi-dung')};
exports.lessonCreate=async(req,res)=>{await L.createLesson(req.body.book_id,req.body.title,req.body.content,req.body.is_preview==='on',req.body.chapter_id);res.redirect('/admin/sach/'+req.body.book_id+'/noi-dung')};
exports.lessonDelete=async(req,res)=>{await L.deleteLesson(req.params.id);res.redirect('/admin/sach/'+req.body.book_id+'/noi-dung')};
exports.videoCreate=async(req,res)=>{let v=req.body.source_value||'';if(req.body.source_type==='upload'&&req.file)v='/uploads/videos/'+req.file.filename;await L.addVideo(req.body.lesson_id,{title:req.body.title,source_type:req.body.source_type,source_value:v,duration_seconds:req.body.duration_seconds,is_free:req.body.is_free==='on'});res.redirect('/admin/sach/'+req.body.book_id+'/noi-dung')};
exports.fileCreate=async(req,res)=>{let u=req.body.file_url_link,ft='pdf';if(req.file){u='/uploads/files/'+req.file.filename;ft=(req.file.originalname.split('.').pop()||'pdf').toLowerCase()}if(u)await L.addFile(req.body.lesson_id,{title:req.body.title,file_url:u,file_type:ft,is_free:req.body.is_free==='on'});res.redirect('/admin/sach/'+req.body.book_id+'/noi-dung')};
