const crypto=require('crypto');
const axios=require('axios');
const db=require('../config/db');

const MAX_STUDENTS_PER_CLASS=5000;
function code(){return crypto.randomBytes(4).toString('hex').toUpperCase();}
function studentCode(){return 'HS'+crypto.randomBytes(4).toString('hex').toUpperCase();}
function activeUser(req){return req.session.adminUser||req.session.user||null;}
function isAdmin(user){return Boolean(user && ['super_admin','admin'].includes(user.role));}
async function ensureRoomSettings(roomId){await db.query('INSERT INTO classroom_settings(classroom_id) VALUES($1) ON CONFLICT (classroom_id) DO NOTHING',[roomId]);}
async function getMembers(roomId){return (await db.query(`SELECT cs.*,u.name AS account_name,u.email FROM classroom_students cs LEFT JOIN users u ON u.id=cs.user_id WHERE cs.classroom_id=$1 ORDER BY cs.id`,[roomId])).rows;}
async function hasRoomAccess(req,room){
  const user=activeUser(req);
  if(user&&(Number(user.id)===Number(room.teacher_id)||isAdmin(user)))return true;
  const memberId=req.session.classroomMembers?.[room.id];
  if(memberId){const m=(await db.query("SELECT id FROM classroom_students WHERE id=$1 AND classroom_id=$2 AND status='active'",[memberId,room.id])).rows[0];if(m)return true;}
  if(user?.id){const m=(await db.query("SELECT id FROM classroom_students WHERE classroom_id=$1 AND user_id=$2 AND status='active'",[room.id,user.id])).rows[0];if(m)return true;}
  return false;
}

exports.list=async(req,res)=>{const rooms=(await db.query(`SELECT c.*,u.name teacher_name,(SELECT count(*) FROM classroom_students cs WHERE cs.classroom_id=c.id AND cs.status='active')::int student_count FROM classrooms c LEFT JOIN users u ON u.id=c.teacher_id WHERE c.status='live' ORDER BY c.created_at DESC`)).rows;res.render('classrooms',{rooms});};
exports.adminList=async(req,res)=>{const rooms=(await db.query(`SELECT c.*,u.name teacher_name,(SELECT count(*) FROM classroom_students cs WHERE cs.classroom_id=c.id AND cs.status='active')::int student_count,(SELECT count(*) FROM classroom_students cs WHERE cs.classroom_id=c.id AND cs.last_seen > now()-interval '2 minutes')::int online_count FROM classrooms c LEFT JOIN users u ON u.id=c.teacher_id ORDER BY CASE WHEN c.status='live' THEN 0 ELSE 1 END,c.created_at DESC`)).rows;res.render('admin/classrooms',{rooms,adminUser:req.session.adminUser||req.session.user});};

exports.create=async(req,res)=>{const teacher=activeUser(req);let roomCode=code();for(let i=0;i<8;i++){const x=await db.query('SELECT 1 FROM classrooms WHERE room_code=$1',[roomCode]);if(!x.rows.length)break;roomCode=code();}const r=await db.query(`INSERT INTO classrooms(room_code,title,teacher_id,status,live_url,pdf_url) VALUES($1,$2,$3,'live',$4,$5) RETURNING *`,[roomCode,req.body.title||'Phòng học mới',teacher?.id||null,req.body.live_url||null,req.body.pdf_url||null]);await ensureRoomSettings(r.rows[0].id);const count=Math.max(0,Math.min(MAX_STUDENTS_PER_CLASS,parseInt(req.body.student_count||'0',10)||0));const prefix=String(req.body.student_prefix||'HS').trim().toUpperCase().replace(/[^A-Z0-9_-]/g,'').slice(0,12)||'HS';if(count){const client=await db.getClient();try{await client.query('BEGIN');for(let i=1;i<=count;i++){let sc=`${prefix}${String(i).padStart(3,'0')}`;for(let n=0;n<5;n++){const exists=await client.query('SELECT 1 FROM classroom_students WHERE student_code=$1',[sc]);if(!exists.rows.length)break;sc=studentCode();}await client.query('INSERT INTO classroom_students(classroom_id,student_code,display_name) VALUES($1,$2,$3)',[r.rows[0].id,sc,`Học viên ${i}`]);}await client.query('COMMIT');}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}res.redirect('/admin/phong-hoc/'+r.rows[0].id);};

exports.close=async(req,res)=>{await db.query("UPDATE classrooms SET status='closed' WHERE id=$1",[req.params.id]);res.redirect('/admin/phong-hoc');};
exports.adminRoom=async(req,res)=>{const room=(await db.query(`SELECT c.*,u.name teacher_name FROM classrooms c LEFT JOIN users u ON u.id=c.teacher_id WHERE c.id=$1`,[req.params.id])).rows[0];if(!room)return res.status(404).render('404');await ensureRoomSettings(room.id);const [students,settings]=await Promise.all([getMembers(room.id),db.query('SELECT * FROM classroom_settings WHERE classroom_id=$1',[room.id])]);res.render('admin/classroom-detail',{room,students,settings:settings.rows[0],adminUser:req.session.adminUser||req.session.user});};
exports.addStudents=async(req,res)=>{const roomId=Number(req.params.id);const current=(await db.query('SELECT count(*)::int AS n FROM classroom_students WHERE classroom_id=$1',[roomId])).rows[0]?.n||0;const available=Math.max(0,MAX_STUDENTS_PER_CLASS-current);const count=Math.max(0,Math.min(available,parseInt(req.body.count||'0',10)||0));const start=Math.max(1,parseInt(req.body.start_number||'1',10)||1);const prefix=String(req.body.prefix||'HS').trim().toUpperCase().replace(/[^A-Z0-9_-]/g,'').slice(0,12)||'HS';for(let i=0;i<count;i++){const n=start+i;let sc=`${prefix}${String(n).padStart(3,'0')}`;const exists=await db.query('SELECT 1 FROM classroom_students WHERE student_code=$1',[sc]);if(exists.rows.length)sc=studentCode();await db.query('INSERT INTO classroom_students(classroom_id,student_code,display_name) VALUES($1,$2,$3)',[roomId,sc,`Học viên ${n}`]);}res.redirect('/admin/phong-hoc/'+roomId);};
exports.updateStudent=async(req,res)=>{const roomId=Number(req.params.id);const studentId=Number(req.params.studentId);const canWrite=String(req.body.can_write)==='true';const status=req.body.status==='blocked'?'blocked':'active';const name=String(req.body.display_name||'').trim().slice(0,120);await db.query(`UPDATE classroom_students SET display_name=COALESCE(NULLIF($1,''),display_name),can_write=$2,status=$3 WHERE id=$4 AND classroom_id=$5`,[name,canWrite,status,studentId,roomId]);res.redirect('/admin/phong-hoc/'+roomId);};
exports.deleteStudent=async(req,res)=>{await db.query('DELETE FROM classroom_students WHERE id=$1 AND classroom_id=$2',[req.params.studentId,req.params.id]);res.redirect('/admin/phong-hoc/'+req.params.id);};
exports.settings=async(req,res)=>{const enabled=String(req.body.ask_teacher_enabled)!=='false';await ensureRoomSettings(req.params.id);await db.query('UPDATE classroom_settings SET ask_teacher_enabled=$1,updated_at=now() WHERE classroom_id=$2',[enabled,req.params.id]);res.redirect('/admin/phong-hoc/'+req.params.id);};

exports.room=async(req,res)=>{const room=(await db.query(`SELECT c.*,u.name teacher_name FROM classrooms c LEFT JOIN users u ON u.id=c.teacher_id WHERE room_code=$1`,[req.params.code])).rows[0];if(!room)return res.status(404).render('404');await ensureRoomSettings(room.id);const user=activeUser(req);let member=null;if(user?.id)member=(await db.query("SELECT * FROM classroom_students WHERE classroom_id=$1 AND user_id=$2 AND status='active' LIMIT 1",[room.id,user.id])).rows[0]||null;if(!member&&req.session.classroomMembers?.[room.id])member=(await db.query("SELECT * FROM classroom_students WHERE id=$1 AND classroom_id=$2 AND status='active'",[req.session.classroomMembers[room.id],room.id])).rows[0]||null;const materials=(await db.query('SELECT * FROM classroom_materials WHERE classroom_id=$1 ORDER BY position,id',[room.id])).rows;const settings=(await db.query('SELECT * FROM classroom_settings WHERE classroom_id=$1',[room.id])).rows[0];const isTeacher=Boolean(user&&(Number(user.id)===Number(room.teacher_id)||isAdmin(user)));if(member)await db.query('UPDATE classroom_students SET last_seen=now() WHERE id=$1',[member.id]);res.render('classroom',{room,materials,isTeacher,member,settings});};
exports.joinByCode=async(req,res)=>{const room=(await db.query("SELECT id,room_code FROM classrooms WHERE room_code=$1 AND status='live'",[req.params.code])).rows[0];if(!room)return res.status(404).send('Không tìm thấy lớp học.');const sc=String(req.body.student_code||'').trim().toUpperCase();const member=(await db.query("SELECT * FROM classroom_students WHERE classroom_id=$1 AND student_code=$2 AND status='active'",[room.id,sc])).rows[0];if(!member)return res.status(401).render('classroom-access',{room,error:'Mã học viên không đúng hoặc học viên đã bị khóa.'});req.session.classroomMembers=req.session.classroomMembers||{};req.session.classroomMembers[room.id]=member.id;member.last_seen=new Date();req.session.save(()=>res.redirect('/phong-hoc/'+room.room_code));};
exports.addMaterial=async(req,res)=>{await db.query('INSERT INTO classroom_materials(classroom_id,title,kind,url) VALUES($1,$2,$3,$4)',[req.body.classroom_id,req.body.title,req.body.kind||'link',req.body.url||null]);res.redirect('/phong-hoc/'+req.body.room_code);};

function extractDriveId(url){const m=String(url||'').match(/drive\.google\.com\/(?:file\/d\/|open\?id=|uc\?(?:[^#]*&)?id=)([^/?&#]+)/i);return m?.[1]||null;}
async function downloadPdf(url){const driveId=extractDriveId(url);const candidates=[];if(driveId){candidates.push(`https://drive.usercontent.google.com/download?id=${encodeURIComponent(driveId)}&export=download&confirm=t`);candidates.push(`https://drive.google.com/uc?export=download&id=${encodeURIComponent(driveId)}&confirm=t`);}candidates.push(url);let lastError=null;for(const candidate of candidates){try{const up=await axios.get(candidate,{responseType:'arraybuffer',maxRedirects:8,timeout:30000,headers:{'User-Agent':'Mozilla/5.0','Accept':'application/pdf,application/octet-stream,*/*'}});const data=Buffer.from(up.data);const contentType=String(up.headers['content-type']||'').toLowerCase();const isPdf=data.subarray(0,4).toString('ascii')==='%PDF'||contentType.includes('application/pdf');if(isPdf)return {data,contentType:'application/pdf'};lastError=new Error(`Nguồn không trả về PDF (${contentType||'không có content-type'})`);}catch(e){lastError=e;}}throw lastError||new Error('Không tải được PDF');}
exports.pdf=async(req,res)=>{const room=(await db.query('SELECT id,teacher_id,pdf_url FROM classrooms WHERE room_code=$1',[req.params.code])).rows[0];if(!room?.pdf_url)return res.status(404).send('Phòng học chưa có PDF.');if(!(await hasRoomAccess(req,room)))return res.status(403).send('Bạn chưa được cấp quyền vào tài liệu của lớp.');try{const pdf=await downloadPdf(room.pdf_url.trim());res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Length',String(pdf.data.length));res.setHeader('Cache-Control','private,max-age=300');res.setHeader('Content-Disposition','inline; filename="bai-giang.pdf"');return res.status(200).send(pdf.data);}catch(e){console.error('Loi tai PDF phong hoc:',e.message);return res.status(502).send('Không tải được PDF của phòng học.');}};
