const db=require('../config/db');
const BookLearning={
 async chapters(book_id){return(await db.query('SELECT * FROM book_chapters WHERE book_id=$1 ORDER BY position,id',[book_id])).rows},
 async createChapter(book_id,title){const p=await db.query('SELECT COALESCE(MAX(position),0)+1 p FROM book_chapters WHERE book_id=$1',[book_id]);return(await db.query('INSERT INTO book_chapters(book_id,title,position) VALUES($1,$2,$3) RETURNING *',[book_id,title,p.rows[0].p])).rows[0]},
 async reorderChapters(ids){for(let i=0;i<ids.length;i++)await db.query('UPDATE book_chapters SET position=$1 WHERE id=$2',[i,ids[i]])},
 async deleteChapter(id){await db.query('DELETE FROM book_chapters WHERE id=$1',[id])},
 async lessons(book_id){const rows=(await db.query(`SELECT l.*,c.title chapter_title,c.position chapter_position FROM book_lessons l LEFT JOIN book_chapters c ON c.id=l.chapter_id WHERE l.book_id=$1 ORDER BY c.position,c.id,l.position,l.id`,[book_id])).rows;return Promise.all(rows.map(async l=>{l.videos=(await db.query('SELECT * FROM book_lesson_videos WHERE lesson_id=$1 ORDER BY position,id',[l.id])).rows;l.files=(await db.query('SELECT * FROM book_lesson_files WHERE lesson_id=$1 ORDER BY position,id',[l.id])).rows;l.quiz=(await db.query('SELECT id,title,pass_score FROM book_quizzes WHERE lesson_id=$1 LIMIT 1',[l.id])).rows[0]||null;return l}))},
 async createLesson(book_id,title,content,is_preview,chapter_id){const p=await db.query('SELECT COALESCE(MAX(position),0)+1 p FROM book_lessons WHERE book_id=$1',[book_id]);return(await db.query('INSERT INTO book_lessons(book_id,chapter_id,title,content,is_preview,position) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[book_id,chapter_id||null,title,content||'',is_preview?1:0,p.rows[0].p])).rows[0]},
 async addVideo(lesson_id,data){const p=await db.query('SELECT COALESCE(MAX(position),0)+1 p FROM book_lesson_videos WHERE lesson_id=$1',[lesson_id]);return(await db.query('INSERT INTO book_lesson_videos(lesson_id,title,source_type,source_value,duration_seconds,is_free,position) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[lesson_id,data.title,data.source_type,data.source_value,data.duration_seconds||null,data.is_free?1:0,p.rows[0].p])).rows[0]},
 async addFile(lesson_id,data){const p=await db.query('SELECT COALESCE(MAX(position),0)+1 p FROM book_lesson_files WHERE lesson_id=$1',[lesson_id]);return(await db.query('INSERT INTO book_lesson_files(lesson_id,title,file_url,file_type,is_free,position) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[lesson_id,data.title,data.file_url,data.file_type||'pdf',data.is_free?1:0,p.rows[0].p])).rows[0]},
 async deleteLesson(id){await db.query('DELETE FROM book_lessons WHERE id=$1',[id])},
 async getLesson(id){const l=(await db.query('SELECT l.*,b.title book_title,b.slug book_slug FROM book_lessons l JOIN books b ON b.id=l.book_id WHERE l.id=$1',[id])).rows[0];if(!l)return null;l.videos=(await db.query('SELECT * FROM book_lesson_videos WHERE lesson_id=$1 ORDER BY position,id',[id])).rows;l.files=(await db.query('SELECT * FROM book_lesson_files WHERE lesson_id=$1 ORDER BY position,id',[id])).rows;l.quiz=(await db.query('SELECT id,title,pass_score FROM book_quizzes WHERE lesson_id=$1 LIMIT 1',[id])).rows[0]||null;return l}
};module.exports=BookLearning;
